### ISSUE TITLE
Test updated to use the actual IRI

### ISSUE THREAD

**Issue by hartig** [awslabs/SPARQL-CDTs#1]
@kasei I have created permanent identifiers for the two datatypes, for the SPARQL functions, and for the spec. With this, the IRI prefix that our usual `cdt:` prefix name maps to is
`https://w3id.org/awslabs/neptune/SPARQL-CDTs/`  

Hence,
* `cdt:List` is https://w3id.org/awslabs/neptune/SPARQL-CDTs/List
* `cdt:Map` is https://w3id.org/awslabs/neptune/SPARQL-CDTs/Map
* `cdt:contains` is https://w3id.org/awslabs/neptune/SPARQL-CDTs/contains
* etc.

I have changed the spec accordingly, and updated all the tests (see commit https://github.com/awslabs/SPARQL-CDTs/commit/2a9f6e988a2795fb530230593a7a33bc91802ef8).

You can use this issue as a reminder to update your implementation. Once you have updated it and it can run the updated tests, you can close this issue.

**Comment by kasei** [comment]
I've updated the namespace prefix in my implementation. I still have a few tests that are not passing, but unrelated to this change. I'm happy to see this closed, but I don't think I have permissions to do that in the awslabs' repo.

**Comment by hartig** [comment]
Thanks Greg! I close it then.
